### ISSUE TITLE
HTTP Error 500

### ISSUE THREAD

**Issue by Jaelski** [ryanmab/CensorDodge#1]
Hi! I was testing out the script. I got a fresh install of centos 7. Installed php, php-xml, curl, and apache. Put the files in the root directory. When I was trying it out. It just shows http error. Am I missing a crucial step to make this work?

**Comment by ryanmab** [comment]
Hi @Jaelski,
In all honestly, I don't think this is the script. In general, it doesn't need anything special, and works fine on even very in-expensive shared hosting. 

It may be related to the server configuration. If you have a look through the apache logs they may shed some light on the issue - If you could give me any more information I'm happy to help however I can.

Thanks,
Ryan

**Comment by Jaelski** [comment]
Hi @ryanmab,

Apache error logs seems to show this:

[Wed Apr 21 16:28:29.595790 2021] [:error] [pid 8509] [client 172.27.246.37:64268] PHP Fatal error:  Can't use function return value in write context in /var/www/html/includes/class.censorDodge.php on line 692

**Comment by Jaelski** [comment]
Hi @ryanmab,

What could possibly be the reason why that error pops up when I access censor dodge (hosted on my test centos web server)? Hope you could help me out on this one. Not really super familiar with PHP.

**Comment by ryanmab** [comment]
Hi @Jaelski,
Thanks for getting back to me. Very interesting, I've never encountered this error before. Do you know what PHP version you're running?

Thanks,
Ryan

**Comment by Jaelski** [comment]
Hi @ryanmab,

It seems I'm running PHP 5.4.16. Is that the issue here?

**Comment by Jaelski** [comment]
Hi @ryanmab ,

PHP version seem to have been the issue. It's working now. Thank you!
