### ISSUE TITLE
writing permissions 

### ISSUE THREAD

**Issue by starboy20000** [ryanmab/CensorDodge#15]
when i load the index.php it says You need to have the file writing permissions enabled to use Censor Dodge V1.83 BETA!

**Comment by ryanmab** [comment]
Hi @starboy20000,
Thanks for raising this! So this is Censor Dodge saying that it cannot create the directory on your server that it needs to store users cookies. 

You'll need to allow write permissions to the directory that Censor Dodge is trying to create the cookie files in - this may either be, by default, the temporary directory your server (see: [sys_get_temp_dir()](https://www.php.net/manual/en/function.sys-get-temp-dir.php)), or the `includes` folder, depending on your configuration.

Thanks,
Ryan
