### ISSUE TITLE
Error : You need to have the file writing permissions enabled to use Censor Dodge...

### ISSUE THREAD

**Issue by manzing** [ryanmab/CensorDodge#23]
Hello
I extracted the files on my apache web server (debian VPS), which comply all prerequisites.
All i got is this error message : You need to have the file writing permissions enabled to use Censor Dodge V1.83 BETA!

After I set permissions on includes folder, I now have a blank page, but nothing better.

php log, only one error : 
 PHP Warning:  Module "curl" is already loaded in Unknown on line 0
What can I do?

**Comment by ryanmab** [comment]
Hi @manzing,
So you're totally right, you need to make sure to grant write permissions on your server!

In terms of the error you receive after setting up the write permissions, that might be an issue with the server configuration, rather than Censor Dodge itself. Here's an [example of a similar issue](https://stackoverflow.com/a/44572697).

Do you have anything else using PHP which runs successfully on your server?

Thanks,
Ryan

**Comment by manzing** [comment]
Thnaks for your answer @ryanmab 

I have a working wordpress website, and beforeCensor Dodge I tried php-proxy, for which I had to enable curl in php.ini.
I tried to revert this settings but the page remains blank.
No other php / curl extension is configured in any other files (I made a grep on php folder to be sure).
I really have no clue, as I said, I have only this error in php log, nothing else.
If have disabled curl extension, I still have a blank page without any error in log, weird.

I think I will try docker version tomorrow but not sure it will be different.

**Comment by manzing** [comment]
@ryanmab 
Imade some new attempts: 
No error in php log, still blank page.

Tried docker version, but I keep ending on error page: 
`Forbidden
You don't have permission to access this resource.
Apache/2.4.38 (Debian) Server at myserver Port 80`

Server side I can see this

`[Wed Mar 15 09:33:59.905431 2023] [autoindex:error] [pid 20] [client 172.17.0.1:37062] AH01276: Cannot serve directory /var/www/html/: No matching DirectoryIndex (index.php,index.html) found, and server-generated directory index forbidden by Options directive`

I have to mention that I have a Apache server running locally, and nginx. Nginx is configurerd with https and redirect requests on localhost and port choosed for CensorDodge container.

Any suggestion?

**Comment by manzing** [comment]
After some testing : 

V1.83 Beta is obviously NOT compatible with PHP 8.1. I pulled files from master and replace my existing installation and the page appeared, but with issues : no background, proxy not functionnal.
This is due to nginx, if I bypass the reverse proxy CensorDodge is OK and works fine, with some broken images / scripts but like every other php proxy.
