### ISSUE TITLE
invalid input issue

### ISSUE THREAD

**Issue by acoul** [ryanmab/CensorDodge#6]
when I enter a valid host/domain or IP address th

at is not permitted by the blacklist rules, the error message is properly displayed on the browser

in case the input is an invalid string, such as `zzzzzzzzzzzzzzzzzz` or `1111111111111111111`, then the error page is a text message on the browser with html code 

if you save that text/html code to a file, it's then properly displayed on the browser instead of the original text/html code output

[error_html.txt](https://github.com/ryanmab/CensorDodge/files/6400752/error_html.txt)

**Comment by ryanmab** [comment]
Hi @acoul,
Thanks for getting in touch about this! Could you send me a video demonstrating this issue so I can look at getting it fixed?

Thanks,
Ryan
